version: 2
updates:
  # CI
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    commit-message:
      prefix: ci
    labels: ["skip changelog"]
    groups:
      ci:
        patterns:
          - "*"

  # Python
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    commit-message:
      prefix: build
      prefix-development: chore
    labels: ["skip changelog"]
    groups:
      python:
        patterns:
          - "*"
